excerpt_separator: ""
pygments: true
markdown: kramdown
title: Jacob deCastro
tagline: Writer + Visual Designer
description: Writing, designing, running, and cycling out of Indianapolis, IN.
paginate: 5
